//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
        [Required(ErrorMessage = "{0}Không được để trống")]
        [Display(Name = "Mã Khách Hàng")] //thuộc tính display rename column
        public int MaKH { get; set; }
        [Required(ErrorMessage = "{0}Không được để trống")]
        [Display(Name = "Họ Tên")]
        public string HoTen { get; set; }
        [Required(ErrorMessage = "{0}Không được để trống")]
        [Display(Name = "Tài Khoản")]
        public string TaiKhoan { get; set; }
        [Required(ErrorMessage = "{0}Không được để trống")]
        [Display(Name = "Mật Khẩu")]
        [DataType(DataType.Password)]
        public string MatKhau { get; set; }
        [Required(ErrorMessage = "{0}Không được để trống")]
        [Display(Name = "Địa chỉ Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "{0}Không được để trống")]
        [Display(Name = "Địa chỉ")]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "{0}Không được để trống")]
        [Display(Name = "Số Điện Thoại")]
        public string DienThoai { get; set; }
        [Required(ErrorMessage = "{0}Không được để trống")]
        [Display(Name = "Giới Tính")]
        public string GioiTinh { get; set; }
        [Display(Name = "Ngày sinh")]
        //[Required(ErrorMessage = "{0} không được để trống")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgaySinh { get; set; }

        [Required(ErrorMessage = "{0}Không được để trống")]
        [Display(Name = "Quyền hạn")]
        [Range(0, 1, ErrorMessage = "{0} phải thuộc [0, 1] 0: Khách hàng, 1: Admin")]
        public Nullable<int> Quyen { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
